Repository OCSInventory-NG/OCSInventory-ocsreports, pull requests merged in 2018-08, with the labels that each got.

#526 Fix privacy
  templates/OCS_template.html
Labels: enhancement

#525 Notification improvement
  plugins/language/en_GB/en_GB.txt
  plugins/language/fr_FR/fr_FR.txt
  plugins/main_sections/ms_config/ms_notification.php
  require/mail/NotificationMail.php
  templates/.htaccess
Labels: enhancement

#529 Update brazilian translation
  plugins/language/br_BR/br_BR.txt
Labels: enhancement

#527 Fix declaration in cd repository
  plugins/computer_detail/cd_repository/cd_repository.php
Labels: bug, enhancement

#555 Fix search by last inventory and contact
  plugins/language/br_BR/br_BR.txt
  plugins/language/en_GB/en_GB.txt
  plugins/language/fr_FR/fr_FR.txt
  require/search/Search.php
  require/search/TranslationSearch.php
Labels: bug, enhancement

#554 Fix to https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/553
  plugins/main_sections/ms_teledeploy/ms_speed_stat.php
Labels: bug, enhancement

#551 Security Fix search outside tag restrictions
  require/search/Search.php
Labels: bug, enhancement

#564 Fix bug dynamic group replay query
  plugins/main_sections/ms_groups/ms_group_show.php
Labels: bug

#557 Fix #535
  require/function_console.php
  require/search/Search.php
Labels: bug

#563 Fix #562
  plugins/language/br_BR/br_BR.txt
  plugins/language/de_DE/de_DE.txt
  plugins/language/es_ES/es_ES.txt
  plugins/language/it_IT/it_IT.txt
  plugins/language/pl_PL/pl_PL.txt
  plugins/language/pt_PT/pt_PT.txt
  plugins/language/si_SI/si_SI.txt
  plugins/language/tr_TR/tr_TR.txt
  plugins/language/ug_UY/ug_UY.txt
Labels: bug

#550 Fix #545
  require/function_table_html.php
Labels: bug

#549 Fix #548
  plugins/main_sections/ms_admininfo/ms_admininfo.php
Labels: bug

#568 Add group search
  plugins/language/en_GB/en_GB.txt
  plugins/language/fr_FR/fr_FR.txt
  plugins/main_sections/ms_multi_search/ms_multi_search.php
  require/search/DatabaseSearch.php
  require/search/GroupSearch.php
  require/search/Search.php
  require/search/TranslationSearch.php
Labels: enhancement
