Repository OCSInventory-NG/OCSInventory-ocsreports, pull requests merged in 2018-07, with the labels that each got.

#492 Fix #491
  require/function_table_html.php
Labels: bug

#499 Fix bug radio button administrative data
  require/function_commun.php
Labels: bug

#503 Add advanced configuration
  plugins/language/en_GB/en_GB.txt
  plugins/language/fr_FR/fr_FR.txt
  plugins/main_sections/ms_config/ms_config.php
  require/function_config_generale.php
Labels: enhancement

#504 Simplify Administrative data
  plugins/computer_detail/cd_admininfo/cd_admininfo.php
  plugins/language/en_GB/en_GB.txt
  plugins/language/fr_FR/fr_FR.txt
  plugins/main_sections/ms_admininfo/ms_admininfo.php
  plugins/main_sections/ms_multi_search/ms_custom_tag.php
  plugins/snmp_detail/sd_admininfo/sd_admininfo.php
  require/function_admininfo.php
Labels: bug, enhancement

#506 Fix bug Show/Hide acoountInfo
  plugins/main_sections/ms_config/ms_config.php
  require/function_admininfo.php
Labels: bug

#505 Remove Update Old Accountinfo
  config/main_menu.xml
  config/profiles/sadmin.xml
  config/urls.xml
  plugins/main_sections/ms_plugins/functions_check.php
  plugins/main_sections/ms_scripts/ms_update_new_tag.php
Labels: enhancement

#508 Fix bug account info checkbox multi search
  plugins/language/br_BR/br_BR.txt
  plugins/language/cs_CZ/cs_CZ.txt
  plugins/language/de_DE/de_DE.txt
  plugins/language/en_GB/en_GB.txt
  plugins/language/es_ES/es_ES.txt
  plugins/language/fr_FR/fr_FR.txt
  plugins/language/it_IT/it_IT.txt
  plugins/language/ja_JP/ja_JP.txt
  plugins/language/pl_PL/pl_PL.txt
  plugins/language/pt_PT/pt_PT.txt
  plugins/language/ru_RU/ru_RU.txt
  plugins/language/si_SI/si_SI.txt
  plugins/language/tr_TR/tr_TR.txt
  plugins/language/ug_UY/ug_UY.txt
  plugins/language/uk_UA/uk_UA.txt
  plugins/main_sections/ms_multi_search/ms_multi_search.php
Labels: bug

#522 Move bios position to top
  config/computer/plugins.xml
Labels: enhancement

#521 Update slot number translation
  plugins/language/fr_FR/fr_FR.txt
Labels: enhancement
