Repository OCSInventory-NG/OCSInventory-ocsreports, pull requests merged in 2019-01, with the labels that each got.

#651 Fix #646
  require/extensions/ExtensionManager.php
Labels: bug

#654 Fix #645
  require/search/Search.php
Labels: bug

#652 Fix #601
  js/function.js
  plugins/main_sections/ms_config/ms_notification.php
Labels: bug

#655 Fix bug translation extension
  require/extensions/ExtensionHook.php
Labels: bug

#656 Display network interface informations on all computer only with status UP
  plugins/main_sections/ms_all_computers/ms_all_computers.php
Labels: bug, enhancement

#662 Fix #660
  require/function_telediff.php
Labels: bug

#661 Fix bug path writable notification templates
  plugins/language/en_GB/en_GB.txt
  plugins/language/fr_FR/fr_FR.txt
  require/mail/NotificationMail.php
Labels: bug

#670 Add DEB package in issue template
  .github/ISSUE_TEMPLATE.md
Labels: enhancement

#672 Do not search in 'Count' column in ms_all_soft.php
  plugins/main_sections/ms_all_soft/ms_all_soft.php
Labels: enhancement

#679 Fix CVE-2018-19602
  plugins/main_sections/ms_computer/ms_computer_views.php
Labels: bug

#680 Add having and not having for accountinfo checkbox in multisearch
  require/function_admininfo.php
  require/search/AccountinfoSearch.php
  require/search/Search.php
  require/search/TranslationSearch.php
Labels: enhancement

#675 Do not read the whole log file anymore when exporting it.
  plugins/main_sections/ms_export/ms_csv.php
Labels: bug, enhancement
