Repository OCSInventory-NG/OCSInventory-ocsreports, pull requests merged in 2020-02, with the labels that each got.

#899 Fix #867
  crontab/cron_cve.php
  plugins/language/en_GB/en_GB.txt
  plugins/language/fr_FR/fr_FR.txt
  plugins/main_sections/ms_all_soft/ms_all_soft.php
  plugins/main_sections/ms_cve_search/ms_cve_search.php
  require/cve/Cve.php
  require/function_config_generale.php
Labels: bug

#898 Fix bug display number for Assets and software categories on dashboard
  plugins/main_sections/ms_all_soft/ms_all_soft.php
  require/console/Console.php
Labels: bug

#907 Add MySQL port on install
  install.php
  require/function_commun.php
Labels: enhancement

#906 Fix #892
  plugins/main_sections/ms_teledeploy/ms_tele_package.php
Labels: bug

#733 found an hard link in the mail cron
  tools/cron_mailer.php
Labels: bug, enhancement, need approval

#910 Change regvalue to TEXT
  files/update/7028.sql
  var.php
Labels: enhancement

#911 Fix #903
  plugins/main_sections/ms_all_computers/ms_all_computers.php
Labels: bug
