Repository OCSInventory-NG/OCSInventory-ocsreports, pull requests merged in 2021-07, with the labels that each got.

#1227 Fix dictionary
  plugins/main_sections/ms_dict/ms_dict.php
Labels: enhancement

#1228 Fix duplicates
  plugins/main_sections/ms_doubles/ms_doubles.php
Labels: bug

#1232 Fix bug display success stat deployment
  plugins/main_sections/ms_teledeploy/ms_speed_stat.php
  require/charts/StatsChartsRenderer.php
Labels: bug

#1230 Fix compatibility with old powershell version
  config/teledeploy/script/removeupdateagent.ps1
  config/teledeploy/script/scheduledupdateagent.ps1
Labels: bug, enhancement

#1240 Fix get hour stat success
  plugins/main_sections/ms_teledeploy/ms_speed_stat.php
Labels: bug
