Repository OCSInventory-NG/OCSInventory-ocsreports, pull requests merged in 2022-10, with the labels that each got.

#1428 add missing parenthesis with is null
  require/search/SQLCache.php
  require/search/Search.php
Labels: bug

#1429 Fix broken multisearch if user restricted to a TAG
  require/search/Search.php
Labels: bug

#1427 Add notification for dynamic group reports
  crontab/cron_report_notification.php
  files/update/7066.sql
  plugins/language/en_GB/en_GB.txt
  plugins/language/fr_FR/fr_FR.txt
  plugins/main_sections/ms_groups/ms_group_show.php
  require/groupReports/GroupReport.php
  templates/OCS_group_notif.html
  var.php
Labels: Feature

#1408 Improve allsoftware - Add new filters
  plugins/language/en_GB/en_GB.txt
  plugins/language/fr_FR/fr_FR.txt
  plugins/main_sections/ms_all_soft/ms_all_soft.php
  require/softwares/AllSoftware.php
Labels: enhancement

#1432 Remove utf-8 encode on software select in software categories
  plugins/main_sections/ms_soft_cat/ms_options_soft_cat.php
Labels: bug

#1399 Security fixes and improvments
  config/computer/plugins.xml
  config/profiles/admin.xml
  config/profiles/ladmin.xml
  config/profiles/sadmin.xml
  config/urls.xml
  plugins/computer_detail/cd_teledeploy/cd_teledeploy.php
  plugins/computer_detail/cd_teledeploymanage/cd_teledeploymanage.php
  plugins/language/en_GB/en_GB.txt
  plugins/language/fr_FR/fr_FR.txt
  plugins/main_sections/ms_admininfo/ms_admininfo.php
  plugins/main_sections/ms_all_computers/ms_all_computers.php
  plugins/main_sections/ms_config/ms_blacklist.php
  plugins/main_sections/ms_dict/ms_dict.php
  plugins/main_sections/ms_groups/ms_group_show.php
  plugins/main_sections/ms_soft_cat/ms_soft_cat.php
  plugins/main_sections/ms_teledeploy/ms_tele_activate.php
  plugins/main_sections/ms_teledeploy/ms_tele_actives.php
  plugins/main_sections/ms_upload_file/ms_upload_file_popup.php
  plugins/main_sections/ms_users/ms_add_profile.php
  plugins/main_sections/ms_users/ms_config_account.php
  plugins/main_sections/ms_users/ms_profile_details.php
  plugins/main_sections/ms_users/ms_user_details.php
  require/function_config_generale.php
  require/function_machine.php
  require/function_table_html.php
  require/function_telediff.php
  require/function_users.php
  require/teledeploy/PackageBuilder.php
Labels: bug, enhancement

#1435 Set charset to utf8 and collate to utf8_general_ci for missing tables
  files/update/7068.sql
  var.php
Labels: enhancement

#1434 Fix php warning
  plugins/main_sections/ms_users/ms_users.php
  plugins/main_sections/ms_users/views/profile_edit_form.php
  require/console/Console.php
  require/function_table_html.php
Labels: bug

#1439 fix rename column syntax not supported
  files/update/7065.sql
  files/update/7069.sql
  var.php
Labels: bug

#1444 Revert commit and fix ms_users
  plugins/main_sections/ms_users/ms_users.php
Labels: bug

#1453 Update empty-sql files
  files/ocsbase.sql
  files/ocsbase_new.sql
Labels: enhancement
