Repository OCSInventory-NG/OCSInventory-ocsreports, pull requests merged in 2024-09, with the labels that each got.

#1624 Security fixes
  plugins/main_sections/ms_export/ms_export_ocs.php
  plugins/main_sections/ms_repart_tag/ms_repart_tag.php
  plugins/main_sections/ms_upload_file/ms_upload_file.php
  require/function_table_html.php
  require/softwares/AllSoftware.php
Labels: bug, enhancement

#1633 fix(cve): fix variable name in Cve class
  require/cve/Cve.php
Labels: bug

#1632 feat(multisearch): add option to ungroup result
  plugins/language/en_GB/en_GB.txt
  plugins/language/fr_FR/fr_FR.txt
  plugins/main_sections/ms_multi_search/ms_multi_search.php
  require/search/Search.php
Labels: Feature
